stages:
  - test
  - build
  - deploy

test-frontend:
  stage: test
  image: node:20
  script:
    - cd frontend
    - npm install
    - npm test

test-backend:
  stage: test
  image: node:20
  script:
    - cd backend
    - npm install
    - npm test
