image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: registry.gitlab.com
  CI_IMAGE: $CI_REGISTRY/csd24-25/workflow-management-system/workflow-management

stages:
  - build
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-frontend:
  stage: build
  script:
    - echo "Building frontend..."
    - docker build -t $CI_IMAGE/my-frontend:latest frontend/
    - docker push $CI_IMAGE/my-frontend:latest

build-backend:
  stage: build
  script:
    - echo "Building backend..."
    - docker build -t $CI_IMAGE/my-backend:latest backend/
    - docker push $CI_IMAGE/my-backend:latest

deploy-frontend:
  stage: deploy
  script:
    - echo "Deploying frontend..."
    - docker pull $CI_IMAGE/my-frontend:latest
    - docker run -d -p 3000:3000 $CI_IMAGE/my-frontend:latest

deploy-backend:
  stage: deploy
  script:
    - echo "Deploying backend..."
    - docker pull $CI_IMAGE/my-backend:latest
    - docker run -d -p 8000:8000 $CI_IMAGE/my-backend:latest
